# Generated by Django 5.1.15 on 2026-08-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationstate',
            new_name='notificatio_user_id_8725da_idx',
            old_name='notif_user_key_idx',
        ),
    ]
