# Generated by Django 5.1.15 on 2026-07-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("credit", "Credit"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10)),
                ("previous_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("new_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoice_adjustments_created", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adjustments", to="sales.invoice")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
