/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as PaymentsNewRouteImport } from './routes/payments.new'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as ExpensesPurchasesRouteImport } from './routes/expenses.purchases'
import { Route as ExpensesCasualsRouteImport } from './routes/expenses.casuals'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as SalesIdEditRouteImport } from './routes/sales.$id.edit'
import { Route as PaymentsIdDocumentRouteImport } from './routes/payments.$id.document'
import { Route as OrdersIdDocumentRouteImport } from './routes/orders.$id.document'
import { Route as CustomersIdStatementRouteImport } from './routes/customers.$id_.statement'
import { Route as ApiPublicOrdersWebhookRouteImport } from './routes/api/public/orders.webhook'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesPurchasesRoute = ExpensesPurchasesRouteImport.update({
  id: '/expenses/purchases',
  path: '/expenses/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesCasualsRoute = ExpensesCasualsRouteImport.update({
  id: '/expenses/casuals',
  path: '/expenses/casuals',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdEditRoute = SalesIdEditRouteImport.update({
  id: '/sales/$id/edit',
  path: '/sales/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIdDocumentRoute = PaymentsIdDocumentRouteImport.update({
  id: '/payments/$id/document',
  path: '/payments/$id/document',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdDocumentRoute = OrdersIdDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => OrdersIdRoute,
} as any)
const CustomersIdStatementRoute = CustomersIdStatementRouteImport.update({
  id: '/customers/$id_/statement',
  path: '/customers/$id/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersWebhookRoute = ApiPublicOrdersWebhookRouteImport.update({
  id: '/api/public/orders/webhook',
  path: '/api/public/orders/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/casuals': typeof ExpensesCasualsRoute
  '/expenses/purchases': typeof ExpensesPurchasesRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/sales/new': typeof SalesNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/orders/$id/document': typeof OrdersIdDocumentRoute
  '/payments/$id/document': typeof PaymentsIdDocumentRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/api/public/orders/webhook': typeof ApiPublicOrdersWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/casuals': typeof ExpensesCasualsRoute
  '/expenses/purchases': typeof ExpensesPurchasesRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/sales/new': typeof SalesNewRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/orders/$id/document': typeof OrdersIdDocumentRoute
  '/payments/$id/document': typeof PaymentsIdDocumentRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/api/public/orders/webhook': typeof ApiPublicOrdersWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/casuals': typeof ExpensesCasualsRoute
  '/expenses/purchases': typeof ExpensesPurchasesRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/sales/new': typeof SalesNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/customers/$id_/statement': typeof CustomersIdStatementRoute
  '/orders/$id/document': typeof OrdersIdDocumentRoute
  '/payments/$id/document': typeof PaymentsIdDocumentRoute
  '/sales/$id/edit': typeof SalesIdEditRoute
  '/api/public/orders/webhook': typeof ApiPublicOrdersWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/receivables'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/stock'
    | '/transactions'
    | '/customers/$id'
    | '/expenses/casuals'
    | '/expenses/purchases'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/sales/new'
    | '/customers/'
    | '/invoices/'
    | '/orders/'
    | '/products/'
    | '/customers/$id/statement'
    | '/orders/$id/document'
    | '/payments/$id/document'
    | '/sales/$id/edit'
    | '/api/public/orders/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/receivables'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/stock'
    | '/transactions'
    | '/customers/$id'
    | '/expenses/casuals'
    | '/expenses/purchases'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/sales/new'
    | '/customers'
    | '/invoices'
    | '/orders'
    | '/products'
    | '/customers/$id/statement'
    | '/orders/$id/document'
    | '/payments/$id/document'
    | '/sales/$id/edit'
    | '/api/public/orders/webhook'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/receivables'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/stock'
    | '/transactions'
    | '/customers/$id'
    | '/expenses/casuals'
    | '/expenses/purchases'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/sales/new'
    | '/customers/'
    | '/invoices/'
    | '/orders/'
    | '/products/'
    | '/customers/$id_/statement'
    | '/orders/$id/document'
    | '/payments/$id/document'
    | '/sales/$id/edit'
    | '/api/public/orders/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ReceivablesRoute: typeof ReceivablesRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  TransactionsRoute: typeof TransactionsRoute
  CustomersIdRoute: typeof CustomersIdRoute
  ExpensesCasualsRoute: typeof ExpensesCasualsRoute
  ExpensesPurchasesRoute: typeof ExpensesPurchasesRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersNewRoute: typeof OrdersNewRoute
  PaymentsNewRoute: typeof PaymentsNewRoute
  SalesNewRoute: typeof SalesNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  CustomersIdStatementRoute: typeof CustomersIdStatementRoute
  PaymentsIdDocumentRoute: typeof PaymentsIdDocumentRoute
  SalesIdEditRoute: typeof SalesIdEditRoute
  ApiPublicOrdersWebhookRoute: typeof ApiPublicOrdersWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/purchases': {
      id: '/expenses/purchases'
      path: '/expenses/purchases'
      fullPath: '/expenses/purchases'
      preLoaderRoute: typeof ExpensesPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/casuals': {
      id: '/expenses/casuals'
      path: '/expenses/casuals'
      fullPath: '/expenses/casuals'
      preLoaderRoute: typeof ExpensesCasualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id/edit': {
      id: '/sales/$id/edit'
      path: '/sales/$id/edit'
      fullPath: '/sales/$id/edit'
      preLoaderRoute: typeof SalesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$id/document': {
      id: '/payments/$id/document'
      path: '/payments/$id/document'
      fullPath: '/payments/$id/document'
      preLoaderRoute: typeof PaymentsIdDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/document': {
      id: '/orders/$id/document'
      path: '/document'
      fullPath: '/orders/$id/document'
      preLoaderRoute: typeof OrdersIdDocumentRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/customers/$id_/statement': {
      id: '/customers/$id_/statement'
      path: '/customers/$id/statement'
      fullPath: '/customers/$id/statement'
      preLoaderRoute: typeof CustomersIdStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/webhook': {
      id: '/api/public/orders/webhook'
      path: '/api/public/orders/webhook'
      fullPath: '/api/public/orders/webhook'
      preLoaderRoute: typeof ApiPublicOrdersWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersIdRouteChildren {
  OrdersIdDocumentRoute: typeof OrdersIdDocumentRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdDocumentRoute: OrdersIdDocumentRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ReceivablesRoute: ReceivablesRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  TransactionsRoute: TransactionsRoute,
  CustomersIdRoute: CustomersIdRoute,
  ExpensesCasualsRoute: ExpensesCasualsRoute,
  ExpensesPurchasesRoute: ExpensesPurchasesRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersNewRoute: OrdersNewRoute,
  PaymentsNewRoute: PaymentsNewRoute,
  SalesNewRoute: SalesNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  CustomersIdStatementRoute: CustomersIdStatementRoute,
  PaymentsIdDocumentRoute: PaymentsIdDocumentRoute,
  SalesIdEditRoute: SalesIdEditRoute,
  ApiPublicOrdersWebhookRoute: ApiPublicOrdersWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
